baseurl = "https://www.cowboysysop.com"
DefaultContentLanguage = "fr"
#DefaultContentLanguage = "ja"
title = "Cowboy Sysop"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
disqusShortname = "cowboysysop"
googleAnalytics = "UA-129648198-1"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
#  subtitle = "Build a beautiful and simple website in minutes"
  mainSections = ["post","posts"]
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = false
  fuzzyWordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Sébastien Prud'homme"
  website = "https://www.cowboysysop.com"
  email = "sebastien.prudhomme@gmail.com"
  github = "sebastien-prudhomme"
  gitlab = "sebastien.prudhomme"
  twitter = "sebasprud"
  linkedin = "sébastien-prud-homme-289b71147"

[[languages.fr.menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[languages.fr.menu.main]]
    name = "Tags"
    url = "tags"
    weight = 2

[[languages.fr.menu.main]]
    name = "À propos"
    url = "page/a-propos"
    weight = 3

[[languages.en.menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[languages.en.menu.main]]
    name = "Tags"
    url = "tags"
    weight = 2

[[languages.en.menu.main]]
    name = "About"
    url = "page/about"
    weight = 3

[languages]
  [languages.fr]
    weight = 1
  [languages.en]
    weight = 2
